language: python
python:
  - "3.4"
  
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer  
  sonarqube:
    organization: "paulossjunior-github"
    token:
      secure: 9b9688155add828b5d987d8e56c7c30d499fb00f  

branches:
  only:
    - master
    - desenvolvimento

before_script:
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle

install:
  - pip install -r requirements.txt
  - sonar-scanner 

script: 
  - behave src/BDD/test/features/
  - nosetests src/TDD/test

